# Generated by Django 3.2.16 on 2022-11-11 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira Nome do Usuário', max_length=200, verbose_name='Nome')),
                ('saldo', models.IntegerField(max_length=100, verbose_name='Saldo')),
                ('recarga', models.IntegerField(help_text='Insira valor da Recarga', max_length=100, verbose_name='Recarga')),
                ('numero', models.IntegerField(max_length=100, verbose_name='Número de Bilhetes')),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
